/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PortfolioApp {
    'test': string;
  }
}

declare global {


  interface HTMLPortfolioAppElement extends Components.PortfolioApp, HTMLStencilElement {}
  var HTMLPortfolioAppElement: {
    prototype: HTMLPortfolioAppElement;
    new (): HTMLPortfolioAppElement;
  };
  interface HTMLElementTagNameMap {
    'portfolio-app': HTMLPortfolioAppElement;
  }
}

declare namespace LocalJSX {
  interface PortfolioApp extends JSXBase.HTMLAttributes<HTMLPortfolioAppElement> {
    'test'?: string;
  }

  interface IntrinsicElements {
    'portfolio-app': PortfolioApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


